import React, { useState } from 'react';
import { StyleSheet, Text, View, SafeAreaView, TouchableOpacity, ScrollView, Platform, StatusBar, Image, Modal } from 'react-native';
import { Feather } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const COLORS = {
  charcoal: '#0F172A', teal: '#0D9488', pink: '#E11D48', 
  bg: '#F8FAFC', white: '#FFFFFF', border: '#E2E8F0',
  textMuted: '#64748B', orange: '#F59E0B', green: '#10B981'
};

export default function HistoryPage({ userEmail, historyData, onNavigate, onLogout }) {
  const [selectedReport, setSelectedReport] = useState(null);
  const isMobile = Platform.OS === 'web' ? window.innerWidth <= 600 : false;

  // --- NEW: PDF GENERATION LOGIC ---
  const generatePDF = async (report) => {
    if (!report) return;

    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #0F172A; }
            .header { border-bottom: 2px solid #0D9488; padding-bottom: 20px; margin-bottom: 30px; }
            .title { font-size: 28px; font-weight: bold; margin: 0; }
            .score-badge { float: right; background: #F0FDFA; color: #0D9488; padding: 10px 20px; border-radius: 10px; font-weight: bold; font-size: 18px; }
            .section { margin-top: 30px; }
            .checkpoint-card { border: 1px solid #E2E8F0; border-radius: 12px; padding: 20px; margin-bottom: 20px; page-break-inside: avoid; }
            .cp-img { max-width: 100%; height: 250px; object-fit: contain; border-radius: 8px; margin-top: 15px; border: 1px solid #E2E8F0; }
            .footer { margin-top: 50px; font-size: 12px; color: #64748B; text-align: center; border-top: 1px solid #E2E8F0; padding-top: 20px; }
            .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; margin-bottom: 10px; }
            .badge-good { background: #F0FDFA; color: #0D9488; }
            .badge-bad { background: #FFF1F2; color: #E11D48; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="score-badge">SCORE: ${report.score} / 5.0</div>
            <p style="color: #0D9488; font-weight: bold; letter-spacing: 1px; margin-bottom: 5px;">${report.badge}</p>
            <h1 class="title">5S Audit Report: ${report.zoneName}</h1>
            <p><strong>Auditor:</strong> ${report.auditor} &nbsp;|&nbsp; <strong>Date:</strong> ${report.date}</p>
          </div>

          <div class="section">
            ${report.checkpoints ? Object.keys(report.checkpoints).map((id, index) => {
              const cp = report.checkpoints[id];
              const isGood = cp.score >= 4.0;
              return `
                <div class="checkpoint-card">
                  <div style="display: flex; justify-content: space-between; align-items: center;">
                    <h3 style="margin: 0;">Checkpoint ${index + 1}</h3>
                    <div style="font-weight: bold; font-size: 16px;">Score: ${cp.score} / 5.0</div>
                  </div>
                  <hr style="border: none; border-top: 1px solid #F1F5F9; margin: 15px 0;" />
                  ${cp.analysis_type ? `<div class="badge ${isGood ? 'badge-good' : 'badge-bad'}">${cp.analysis_type.toUpperCase()}</div>` : ''}
                  <p style="color: #475569; line-height: 1.6;"><strong>Feedback:</strong> ${cp.feedback}</p>
                  ${cp.photoUri ? `<img src="${cp.photoUri}" class="cp-img" />` : '<p style="font-style: italic; color: #94A3B8;">No image recorded</p>'}
                </div>
              `;
            }).join('') : '<p>No detailed checkpoint data available for this report.</p>'}
          </div>

          <div class="footer">
            Generated by CheckGrade AI - Laguna Clothing Pvt Ltd
          </div>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      
      // On Web, expo-sharing doesn't work the same way, so we trigger a download
      if (Platform.OS === 'web') {
          window.open(uri, '_blank');
      } else {
          await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf', dialogTitle: `${report.zoneName} Audit Report` });
      }
    } catch (error) {
      console.error("PDF Error:", error);
      alert("Failed to generate PDF report.");
    }
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="dark-content" backgroundColor={COLORS.white} />
      
      {/* GLOBAL TOP NAV */}
      <View style={styles.topNav}>
        <View style={styles.navLeft}>
            <View style={styles.logoBox}>
                <Image source={require('./assets/logo.png')} style={styles.logoImage} />
            </View>
        </View>

        <View style={styles.navCenter}>
            <TouchableOpacity style={styles.navMenuBtn} onPress={() => onNavigate('dashboard')}>
                <Feather name="pie-chart" size={16} color={COLORS.textMuted} />
                {!isMobile && <Text style={styles.navMenuText}>Dashboard</Text>}
            </TouchableOpacity>
            
            <TouchableOpacity style={styles.navMenuBtn} onPress={() => onNavigate('zones')}>
                <Feather name="grid" size={16} color={COLORS.textMuted} />
                {!isMobile && <Text style={styles.navMenuText}>Zones</Text>}
            </TouchableOpacity>

            <TouchableOpacity style={[styles.navMenuBtn, styles.navMenuBtnActive]} disabled>
                <Feather name="archive" size={16} color={COLORS.teal} />
                {!isMobile && <Text style={[styles.navMenuText, styles.navMenuTextActive]}>Vault</Text>}
            </TouchableOpacity>
        </View>

        <View style={styles.navRight}>
            <TouchableOpacity style={styles.explicitLogoutBtn} onPress={onLogout}>
                <Feather name="log-out" size={16} color={COLORS.pink} />
            </TouchableOpacity>
        </View>
      </View>

      <View style={styles.mainContainer}>
        <View style={styles.pageHeader}>
            <View>
                <Text style={styles.welcomeText}>Audit History Vault</Text>
                <Text style={styles.dateText}>Access detailed reports, photos, and AI insights for past audits.</Text>
            </View>
        </View>

        {/* VAULT LIST */}
        <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
          {(!historyData || historyData.length === 0) ? (
            <View style={styles.emptyState}>
              <Feather name="inbox" size={60} color="#CBD5E1" style={{marginBottom: 20}}/>
              <Text style={styles.emptyTitle}>Vault is Empty</Text>
              <Text style={styles.emptySub}>When you complete a zone audit, the full report and photos will be permanently saved here.</Text>
            </View>
          ) : (
            <View style={styles.grid}>
              {historyData.map((record) => (
                <View key={record.id} style={styles.historyCard}>
                  <View style={styles.cardTop}>
                    <View>
                        <View style={styles.badgeRow}>
                            <Text style={styles.cardBadge}>{record.badge}</Text>
                        </View>
                        <Text style={styles.zoneNameText}>{record.zoneName}</Text>
                    </View>
                    <View style={[styles.scoreCircle, { borderColor: record.score >= 4 ? COLORS.green : record.score >= 2.5 ? COLORS.orange : COLORS.red }]}>
                        <Text style={[styles.scoreValue, { color: record.score >= 4 ? COLORS.green : record.score >= 2.5 ? COLORS.orange : COLORS.red }]}>{record.score}</Text>
                    </View>
                  </View>
                  
                  <View style={styles.statsRow}>
                    <Feather name="calendar" size={14} color={COLORS.textMuted} style={{marginRight: 6}} />
                    <Text style={styles.statsText}>{record.date}</Text>
                  </View>
                  <View style={[styles.statsRow, { marginTop: 6 }]}>
                    <Feather name="user" size={14} color={COLORS.textMuted} style={{marginRight: 6}} />
                    <Text style={styles.statsText}>Auditor: {record.auditor}</Text>
                  </View>

                  <View style={styles.divider} />

                  <TouchableOpacity style={styles.viewReportBtn} activeOpacity={0.8} onPress={() => setSelectedReport(record)}>
                    <Text style={styles.viewReportText}>View Full Report</Text>
                    <Feather name="file-text" size={16} color={COLORS.teal} />
                  </TouchableOpacity>
                </View>
              ))}
            </View>
          )}
        </ScrollView>
      </View>

      {/* --- DETAILED REPORT VIEWER MODAL --- */}
      <Modal transparent={true} visible={!!selectedReport} animationType="slide">
        <View style={styles.modalOverlay}>
          <View style={styles.modalCard}>
            
            {/* Modal Header */}
            <View style={styles.modalHeader}>
                <View style={{flex: 1}}>
                    <Text style={styles.modalBadge}>{selectedReport?.badge}</Text>
                    <Text style={styles.modalTitle}>{selectedReport?.zoneName} Audit Report</Text>
                    <Text style={styles.modalSub}>Completed on {selectedReport?.date} by {selectedReport?.auditor}</Text>
                </View>
                <View style={[styles.modalScoreBox, { backgroundColor: selectedReport?.score >= 4 ? '#ECFDF5' : selectedReport?.score >= 2.5 ? '#FFFBEB' : '#FEF2F2' }]}>
                    <Text style={styles.modalScoreLabel}>FINAL SCORE</Text>
                    <Text style={[styles.modalScoreValue, { color: selectedReport?.score >= 4 ? '#065F46' : selectedReport?.score >= 2.5 ? '#B45309' : '#991B1B' }]}>{selectedReport?.score} / 5.0</Text>
                </View>
                
                {/* --- NEW: Button Container for PDF and Close --- */}
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                    <TouchableOpacity onPress={() => generatePDF(selectedReport)} style={[styles.closeBtn, { backgroundColor: COLORS.teal }]}>
                        <Feather name="download" size={24} color={COLORS.white} />
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => setSelectedReport(null)} style={styles.closeBtn}>
                        <Feather name="x" size={24} color={COLORS.charcoal} />
                    </TouchableOpacity>
                </View>
            </View>

            {/* Modal Content: Photos & Feedback */}
            <ScrollView style={styles.modalScroll} showsVerticalScrollIndicator={false}>
                {selectedReport?.checkpoints ? Object.keys(selectedReport.checkpoints).map((cpId, index) => {
                    const cpData = selectedReport.checkpoints[cpId];
                    const isGood = cpData.score >= 4.0;
                    return (
                        <View key={cpId} style={styles.cpRow}>
                            {/* Display the image if it was saved */}
                            <View style={styles.cpImageContainer}>
                                {cpData.photoUri ? (
                                    <Image source={{ uri: cpData.photoUri }} style={styles.cpImage} />
                                ) : (
                                    <View style={styles.cpImagePlaceholder}><Feather name="image" size={24} color="#CBD5E1" /></View>
                                )}
                            </View>
                            
                            {/* Display the AI Feedback */}
                            <View style={styles.cpDetails}>
                                <View style={styles.cpTopRow}>
                                    <Text style={styles.cpNumber}>Checkpoint {index + 1}</Text>
                                    <View style={[styles.cpScoreBadge, { backgroundColor: isGood ? '#F0FDFA' : '#FFF1F2' }]}>
                                        <Text style={[styles.cpScoreText, { color: isGood ? '#0D9488' : '#E11D48' }]}>{cpData.score} / 5.0</Text>
                                    </View>
                                </View>
                                {cpData.analysis_type && (
                                    <Text style={[styles.cpAnalysisType, { color: isGood ? '#0D9488' : '#E11D48' }]}>{cpData.analysis_type.toUpperCase()}</Text>
                                )}
                                <Text style={styles.cpFeedback}>{cpData.feedback}</Text>
                            </View>
                        </View>
                    );
                }) : (
                    <Text style={styles.noDataText}>No detailed checkpoint data was saved for this audit.</Text>
                )}
            </ScrollView>

          </View>
        </View>
      </Modal>

    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.bg },
  topNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.white, paddingHorizontal: 20, height: Platform.OS === 'android' ? 120 : 100, paddingTop: Platform.OS === 'android' ? 25 : 0, borderBottomWidth: 1, borderBottomColor: COLORS.border, zIndex: 10 },
  navLeft: { flexDirection: 'row', alignItems: 'center', width: 250 },
  logoBox: { width: 220, height: 85, justifyContent: 'center', alignItems: 'flex-start' },
  logoImage: { width: '100%', height: '100%', resizeMode: 'contain' },
  navCenter: { flexDirection: 'row', gap: 10, flex: 1, justifyContent: 'center' },
  navMenuBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12 },
  navMenuBtnActive: { backgroundColor: '#F0FDFA' },
  navMenuText: { color: COLORS.textMuted, fontWeight: '700', fontSize: 14, marginLeft: 8 },
  navMenuTextActive: { color: COLORS.teal },
  navRight: { flexDirection: 'row', alignItems: 'center', width: 250, justifyContent: 'flex-end' },
  explicitLogoutBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 8, backgroundColor: '#FFF1F2' },
  
  mainContainer: { flex: 1, maxWidth: 1200, width: '100%', alignSelf: 'center', paddingTop: 40, paddingHorizontal: 20 },
  pageHeader: { marginBottom: 30 },
  welcomeText: { fontSize: 32, fontWeight: '900', color: COLORS.charcoal, letterSpacing: -0.5, marginBottom: 8 },
  dateText: { fontSize: 16, color: COLORS.textMuted, fontWeight: '600' },
  
  scrollContent: { paddingBottom: 60 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 20, justifyContent: 'flex-start' },
  
  historyCard: { backgroundColor: COLORS.white, width: Platform.OS === 'web' && window.innerWidth > 800 ? '48%' : '100%', borderRadius: 20, padding: 25, borderWidth: 1, borderColor: COLORS.border, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.03, shadowRadius: 10, elevation: 3, marginBottom: 10 },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 15 },
  badgeRow: { backgroundColor: '#F1F5F9', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, alignSelf: 'flex-start', marginBottom: 8 },
  cardBadge: { fontSize: 11, fontWeight: '800', color: COLORS.textMuted, letterSpacing: 0.5 },
  zoneNameText: { fontSize: 24, fontWeight: '900', color: COLORS.charcoal },
  
  scoreCircle: { width: 54, height: 54, borderRadius: 27, borderWidth: 3, justifyContent: 'center', alignItems: 'center' },
  scoreValue: { fontSize: 18, fontWeight: '900' },
  
  statsRow: { flexDirection: 'row', alignItems: 'center' },
  statsText: { fontSize: 14, color: COLORS.textMuted, fontWeight: '600' },
  
  divider: { height: 1, backgroundColor: '#F1F5F9', marginVertical: 20 },
  viewReportBtn: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F8FAFC', paddingHorizontal: 18, paddingVertical: 16, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border },
  viewReportText: { color: COLORS.teal, fontSize: 14, fontWeight: '800' },
  
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 100 },
  emptyTitle: { fontSize: 24, fontWeight: '900', color: COLORS.charcoal, marginBottom: 10 },
  emptySub: { fontSize: 16, color: COLORS.textMuted, textAlign: 'center', maxWidth: 450, lineHeight: 26 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.8)', justifyContent: 'center', alignItems: 'center', padding: Platform.OS === 'web' ? 40 : 15 },
  modalCard: { backgroundColor: COLORS.white, width: '100%', maxWidth: 900, height: '95%', borderRadius: 24, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.3, shadowRadius: 30, elevation: 20 },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', padding: 30, backgroundColor: '#F8FAFC', borderBottomWidth: 1, borderBottomColor: COLORS.border },
  modalBadge: { fontSize: 12, fontWeight: '800', color: COLORS.teal, letterSpacing: 1, marginBottom: 6 },
  modalTitle: { fontSize: 28, fontWeight: '900', color: COLORS.charcoal, marginBottom: 6 },
  modalSub: { fontSize: 14, color: COLORS.textMuted, fontWeight: '600' },
  modalScoreBox: { alignItems: 'flex-end', marginRight: 20 },
  modalScoreLabel: { fontSize: 11, fontWeight: '800', color: COLORS.textMuted, letterSpacing: 0.5, marginBottom: 4 },
  modalScoreValue: { fontSize: 26, fontWeight: '900' },
  closeBtn: { padding: 10, backgroundColor: '#E2E8F0', borderRadius: 12 },
  
  modalScroll: { flex: 1, padding: 30 },
  noDataText: { fontSize: 16, color: COLORS.textMuted, fontStyle: 'italic', textAlign: 'center', marginTop: 40 },
  
  cpRow: { flexDirection: Platform.OS === 'web' && window.innerWidth > 600 ? 'row' : 'column', gap: 20, paddingBottom: 25, marginBottom: 25, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  cpImageContainer: { width: Platform.OS === 'web' && window.innerWidth > 600 ? 250 : '100%', height: 180, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: COLORS.border },
  cpImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  cpImagePlaceholder: { flex: 1, backgroundColor: '#F8FAFC', justifyContent: 'center', alignItems: 'center' },
  cpDetails: { flex: 1 },
  cpTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  cpNumber: { fontSize: 16, fontWeight: '800', color: COLORS.charcoal },
  cpScoreBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  cpScoreText: { fontSize: 14, fontWeight: '900' },
  cpAnalysisType: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, marginBottom: 10 },
  cpFeedback: { fontSize: 15, color: '#475569', lineHeight: 24, fontWeight: '500' }
});